[package]
name = "noodles-bed"
version = "0.20.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "BED (Browser Extensible Data) reader"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-bed"

[dependencies]
bstr.workspace = true
lexical-core.workspace = true
memchr.workspace = true
noodles-core = { path = "../noodles-core", version = "0.16.0" }

[dev-dependencies]
noodles-bgzf = { path = "../noodles-bgzf", version = "0.35.0" }
noodles-csi = { path = "../noodles-csi", version = "0.43.0" }
noodles-tabix = { path = "../noodles-tabix", version = "0.49.0" }
