[package]
name = "noodles-bed"
version = "0.15.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "BED (Browser Extensible Data) reader"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-bed"

[dependencies]
lexical-core = "0.8.5"
memchr.workspace = true
noodles-core = { path = "../noodles-core", version = "0.15.0" }
